# Generated by Django 4.0.4 on 2022-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('seekgeek_id', models.IntegerField()),
                ('url', models.URLField()),
                ('pub', models.DateTimeField()),
                ('performer', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
            ],
        ),
    ]
