# Generated by Django 4.0.4 on 2022-05-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_event_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seekgeek_id',
            field=models.IntegerField(unique=True),
        ),
    ]
