# Generated by Django 4.0.4 on 2022-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seekgeek_id',
            field=models.IntegerField(),
        ),
    ]
